class DominosTester
{
   public static void main(String args[])
   {
   double price = 0.0;
  String food;
  food = "Blazing onion and paprika";
  price =Dominos.search(food);
   System.out.println(" Price of the food is "+price);
   food = "Summer special combo";
  price =Dominos.search(food);
   System.out.println(" Price of the food is "+price);
   food = "Summer special party combo";
  price =Dominos.search(food);
   System.out.println(" Price of the food is "+price);
   food = "veg loaded";
  price =Dominos.search(food);
   System.out.println(" Price of the food is "+price);
   food = "Tandoori paneer pizza";
  price =Dominos.search(food);
   System.out.println(" Price of the food is "+price);
   food = "Paneer, onion and capsicum pizza";
  price =Dominos.search(food);
   System.out.println(" Price of the food is "+price);
   food = "Veg extravaganza pizza";
  price =Dominos.search(food);
   System.out.println(" Price of the food is "+price);
   food = "Golden corn";
  price =Dominos.search(food);
   System.out.println(" Price of the food is "+price);
   food = "Margherita pizza";
  price =Dominos.search(food);
   System.out.println(" Price of the food is "+price);
   food = "Farmhouse pizza";
  price =Dominos.search(food);
   System.out.println(" Price of the food is "+price);
   food = "Peppy paneer pizza";
  price =Dominos.search(food);
   System.out.println(" Price of the food is "+price);
   food = "Cheese n corn pizza";
  price =Dominos.search(food);
   System.out.println(" Price of the food is "+price);
   food = "Cheesy pizza";
  price =Dominos.search(food);
   System.out.println(" Price of the food is "+price);
   food = "Veg pizza mania loaded";
  price =Dominos.search(food);
   System.out.println(" Price of the food is "+price);
   food = "Garlic breadstick";
  price =Dominos.search(food);
   System.out.println(" Price of the food is "+price);
   food = "Mexican Green wave pizza";
  price =Dominos.search(food);
   System.out.println(" Price of the food is "+price);
   food = "Capsicum n red paprika";
  price =Dominos.search(food);
   System.out.println(" Price of the food is "+price);
   food = "Onion pizza";
  price =Dominos.search(food);
   System.out.println(" Price of the food is "+price);
   food = "Onion pizza";
  price =Dominos.search(food);
   System.out.println(" Price of the food is "+price);
   food = "Double cheese margherita pizza";
  price =Dominos.search(food);
   System.out.println(" Price of the food is "+price);
   
   
   food = "Blazing onion and paprika";
  price =Dominos.search(food , 2);
   System.out.println(" Price of the food is "+price);
   food = "Summer special combo";
  price =Dominos.search(food , 4);
   System.out.println(" Price of the food is "+price);
   food = "Summer special party combo";
  price =Dominos.search(food , 4);
   System.out.println(" Price of the food is "+price);
   food = "veg loaded";
  price =Dominos.search(food , 5);
   System.out.println(" Price of the food is "+price);
   food = "Tandoori paneer pizza";
  price =Dominos.search(food , 2);
   System.out.println(" Price of the food is "+price);
   food = "Paneer, onion and capsicum pizza";
  price =Dominos.search(food , 2);
   System.out.println(" Price of the food is "+price);
   food = "Veg extravaganza pizza";
  price =Dominos.search(food , 3);
   System.out.println(" Price of the food is "+price);
   food = "Golden corn";
  price =Dominos.search(food , 6);
   System.out.println(" Price of the food is "+price);
   food = "Margherita pizza";
  price =Dominos.search(food , 5);
   System.out.println(" Price of the food is "+price);
   food = "Farmhouse pizza";
  price =Dominos.search(food , 6);
   System.out.println(" Price of the food is "+price);
   food = "Peppy paneer pizza";
  price =Dominos.search(food , 3);
   System.out.println(" Price of the food is "+price);
   food = "Cheese n corn pizza";
  price =Dominos.search(food , 2);
   System.out.println(" Price of the food is "+price);
   food = "Cheesy pizza";
  price =Dominos.search(food , 2);
   System.out.println(" Price of the food is "+price);
   food = "Veg pizza mania loaded";
  price =Dominos.search(food , 1);
   System.out.println(" Price of the food is "+price);
   food = "Garlic breadstick";
  price =Dominos.search(food , 2);
   System.out.println(" Price of the food is "+price);
   food = "Mexican Green wave pizza";
  price =Dominos.search(food, 4);
   System.out.println(" Price of the food is "+price);
   food = "Capsicum n red paprika";
  price =Dominos.search(food , 5);
   System.out.println(" Price of the food is "+price);
   food = "Onion pizza";
  price =Dominos.search(food , 4);
   System.out.println(" Price of the food is "+price);
   food = "Onion pizza";
  price =Dominos.search(food , 2);
   System.out.println(" Price of the food is "+price);
   food = "Double cheese margherita pizza";
  price =Dominos.search(food , 2);
   System.out.println(" Price of the food is "+price);
   }
   }
   