class McDonaldsTester
{
  public static void main(String args[]) 
  {
  double price = 0.0;
  String food;
  food = "Mc veggie burger";
  price =McDonalds.search(food);
   System.out.println(" Price of the food is "+price);
    food = "2 Mc veggie burger combo";
  price =McDonalds.search(food);
   System.out.println(" Price of the food is "+price);
    food = "Fries";
  price =McDonalds.search(food);
   System.out.println(" Price of the food is "+price);
    food = "Big spicy paneer wrap";
  price =McDonalds.search(food);
   System.out.println(" Price of the food is "+price);
    food = "veg maharaja burger";
  price =McDonalds.search(food);
   System.out.println(" Price of the food is "+price);
    food = "Piri piri McSpicy veg burger";
  price =McDonalds.search(food);
   System.out.println(" Price of the food is "+price);
    food = "Corn n cheese burger";
  price =McDonalds.search(food);
   System.out.println(" Price of the food is "+price);
    food = "McAloo tikki";
  price =McDonalds.search(food);
   System.out.println(" Price of the food is "+price);
    food = "Veg maharaja Mac meal";
  price =McDonalds.search(food);
   System.out.println(" Price of the food is "+price);
    food = "Peri peri fries";
  price =McDonalds.search(food);
   System.out.println(" Price of the food is "+price);
    food = "Mexican cheesy fries";
  price =McDonalds.search(food);
   System.out.println(" Price of the food is "+price);
    food = "McVeggie meal";
  price =McDonalds.search(food);
   System.out.println(" Price of the food is "+price);
    food = "Fries medium";
  price =McDonalds.search(food);
   System.out.println(" Price of the food is "+price);
    food = "Mc Aloo tikki combo";
  price =McDonalds.search(food);
   System.out.println(" Price of the food is "+price);
    food = "Garlic cheesy dip";
  price =McDonalds.search(food);
   System.out.println(" Price of the food is "+price);
    food = "piri piri McSpicy Range";
  price =McDonalds.search(food);
   System.out.println(" Price of the food is "+price);
    food = "Piri piri big spicy wrap";
  price =McDonalds.search(food);
   System.out.println(" Price of the food is "+price);
    food = "McCheese veg meal";
  price =McDonalds.search(food);
   System.out.println(" Price of the food is "+price);
    food = "Garlic n cheese veg burger";
  price =McDonalds.search(food);
   System.out.println(" Price of the food is "+price);
   food = "2 coke";
  price =McDonalds.search(food);
   System.out.println(" Price of the food is "+price);
   
   
    food = "Mc veggie burger";
  price =McDonalds.search(food , 2);
   System.out.println(" Price of the food is "+price);
    food = "2 Mc veggie burger combo";
  price =McDonalds.search(food , 2);
   System.out.println(" Price of the food is "+price);
    food = "Fries";
  price =McDonalds.search(food , 3);
   System.out.println(" Price of the food is "+price);
    food = "Big spicy paneer wrap";
  price =McDonalds.search(food , 2);
   System.out.println(" Price of the food is "+price);
    food = "veg maharaja burger";
  price =McDonalds.search(food , 5);
   System.out.println(" Price of the food is "+price);
    food = "Piri piri McSpicy veg burger";
  price =McDonalds.search(food , 4);
   System.out.println(" Price of the food is "+price);
    food = "Corn n cheese burger";
  price =McDonalds.search(food , 4);
   System.out.println(" Price of the food is "+price);
    food = "McAloo tikki";
  price =McDonalds.search(food , 4);
   System.out.println(" Price of the food is "+price);
    food = "Veg maharaja Mac meal";
  price =McDonalds.search(food , 5);
   System.out.println(" Price of the food is "+price);
    food = "Peri peri fries";
  price =McDonalds.search(food , 6);
   System.out.println(" Price of the food is "+price);
    food = "Mexican cheesy fries";
  price =McDonalds.search(food , 2);
   System.out.println(" Price of the food is "+price);
    food = "McVeggie meal";
  price =McDonalds.search(food , 5);
   System.out.println(" Price of the food is "+price);
    food = "Fries medium";
  price =McDonalds.search(food , 5);
   System.out.println(" Price of the food is "+price);
    food = "Mc Aloo tikki combo";
  price =McDonalds.search(food , 4);
   System.out.println(" Price of the food is "+price);
    food = "Garlic cheesy dip";
  price =McDonalds.search(food , 5);
   System.out.println(" Price of the food is "+price);
    food = "piri piri McSpicy Range";
  price =McDonalds.search(food , 6);
   System.out.println(" Price of the food is "+price);
    food = "Piri piri big spicy wrap";
  price =McDonalds.search(food , 8);
   System.out.println(" Price of the food is "+price);
    food = "McCheese veg meal";
  price =McDonalds.search(food , 3);
   System.out.println(" Price of the food is "+price);
    food = "Garlic n cheese veg burger";
  price =McDonalds.search(food , 4);
   System.out.println(" Price of the food is "+price);
   food = "2 coke";
  price =McDonalds.search(food , 3);
   System.out.println(" Price of the food is "+price);
   }
  }