class SwiggyTester
{
public static void main(String args[])
   {
   double price = 0.0;
  String food;
  food = "Lemon rice";
  price =Swiggy.search(food);
   System.out.println(" Price of the food is "+price);
   food = "Pudina rice";
  price =Swiggy.search(food);
   System.out.println(" Price of the food is "+price);
   food = "Bisibele bath";
  price =Swiggy.search(food);
   System.out.println(" Price of the food is "+price);
   food = "Khara bath";
  price =Swiggy.search(food);
   System.out.println(" Price of the food is "+price);
   food = "Gulab jamoon";
  price =Swiggy.search(food);
   System.out.println(" Price of the food is "+price);
   food = "Rasgulla";
  price =Swiggy.search(food);
   System.out.println(" Price of the food is "+price);
   food = "Kesari bath";
  price =Swiggy.search(food);
   System.out.println(" Price of the food is "+price);
   food = "Hyderabadi biryani";
  price =Swiggy.search(food);
   System.out.println(" Price of the food is "+price);
   food = "Aloo parata";
  price =Swiggy.search(food);
   System.out.println(" Price of the food is "+price);
   food = "Vada";
  price =Swiggy.search(food);
   System.out.println(" Price of the food is "+price);
   food = "Chapathi";
  price =Swiggy.search(food);
   System.out.println(" Price of the food is "+price);
   food = "Masal puri";
  price =Swiggy.search(food);
   System.out.println(" Price of the food is "+price);
   food = "Pani puri";
  price =Swiggy.search(food);
   System.out.println(" Price of the food is "+price);
   food = "Curd rice";
  price =Swiggy.search(food);
   System.out.println(" Price of the food is "+price);
   food = "Veg biryani";
  price =Swiggy.search(food);
   System.out.println(" Price of the food is "+price);
   food = "Veg rolls";
  price =Swiggy.search(food);
   System.out.println(" Price of the food is "+price);
   food = "Dahi vada";
  price =Swiggy.search(food);
   System.out.println(" Price of the food is "+price);
   food = "Puliyogare";
  price =Swiggy.search(food);
   System.out.println(" Price of the food is "+price);
   food ="onion pakoda" ;
  price =Swiggy.search(food);
   System.out.println(" Price of the food is "+price);
   food = "bajji";
  price =Swiggy.search(food);
   System.out.println(" Price of the food is "+price);
   
   
   
   food = "Lemon rice";
  price =Swiggy.search(food , 2);
   System.out.println(" Price of the food is "+price);
   food = "Pudina rice";
  price =Swiggy.search(food , 1);
   System.out.println(" Price of the food is "+price);
   food = "Bisibele bath";
  price =Swiggy.search(food , 3);
   System.out.println(" Price of the food is "+price);
   food = "Khara bath";
  price =Swiggy.search(food , 2);
   System.out.println(" Price of the food is "+price);
   food = "Gulab jamoon";
  price =Swiggy.search(food , 3);
   System.out.println(" Price of the food is "+price);
   food = "Rasgulla";
  price =Swiggy.search(food ,2);
   System.out.println(" Price of the food is "+price);
   food = "Kesari bath";
  price =Swiggy.search(food ,3);
   System.out.println(" Price of the food is "+price);
   food = "Hyderabadi biryani";
  price =Swiggy.search(food , 2);
   System.out.println(" Price of the food is "+price);
   food = "Aloo parata";
  price =Swiggy.search(food , 2);
   System.out.println(" Price of the food is "+price);
   food = "Vada";
  price =Swiggy.search(food , 1);
   System.out.println(" Price of the food is "+price);
   food = "Chapathi";
  price =Swiggy.search(food , 1);
   System.out.println(" Price of the food is "+price);
   food = "Masal puri";
  price =Swiggy.search(food , 3);
   System.out.println(" Price of the food is "+price);
   food = "Pani puri";
  price =Swiggy.search(food , 3);
   System.out.println(" Price of the food is "+price);
   food = "Curd rice";
  price =Swiggy.search(food , 3);
   System.out.println(" Price of the food is "+price);
   food = "Veg biryani";
  price =Swiggy.search(food , 2);
   System.out.println(" Price of the food is "+price);
   food = "Veg rolls";
  price =Swiggy.search(food , 2);
   System.out.println(" Price of the food is "+price);
   food = "Dahi vada";
  price =Swiggy.search(food , 4);
   System.out.println(" Price of the food is "+price);
   food = "Puliyogare";
  price =Swiggy.search(food , 4);
   System.out.println(" Price of the food is "+price);
   food ="onion pakoda" ;
  price =Swiggy.search(food ,3);
   System.out.println(" Price of the food is "+price);
   food = "bajji";
  price =Swiggy.search(food , 3);
   System.out.println(" Price of the food is "+price);
   }
}