class UberEatsTester
{
  public static void main(String args[])
  {
    double price = 0.0;
  String food;
  food = "Oreo milkshake";
  price =UberEats.search(food);
   System.out.println(" Price of the food is "+price);
    food = "Chocolate milkshake";
  price =UberEats.search(food);
   System.out.println(" Price of the food is "+price);
    food = "Blueberry shake";
  price =UberEats.search(food);
   System.out.println(" Price of the food is "+price);
    food = "Red sauce pasta";
  price =UberEats.search(food);
   System.out.println(" Price of the food is "+price);
    food = "macroni";
  price =UberEats.search(food);
   System.out.println(" Price of the food is "+price);
    food = "Veg noodles";
  price =UberEats.search(food);
   System.out.println(" Price of the food is "+price);
    food = "Rasam rice";
  price =UberEats.search(food);
   System.out.println(" Price of the food is "+price);
    food = "Loaded cheese fries";
  price =UberEats.search(food);
   System.out.println(" Price of the food is "+price);
    food = "Loaded fries";
  price =UberEats.search(food);
   System.out.println(" Price of the food is "+price);
    food = "Khara bun";
  price =UberEats.search(food);
   System.out.println(" Price of the food is "+price);
    food = "Dum biriyani";
  price =UberEats.search(food);
   System.out.println(" Price of the food is "+price);
    food = "Galebi";
  price =UberEats.search(food);
   System.out.println(" Price of the food is "+price);
    food = "Pepsi";
  price =UberEats.search(food);
   System.out.println(" Price of the food is "+price);
    food = "Veg mania loaded";
  price =UberEats.search(food);
   System.out.println(" Price of the food is "+price);
    food = "Garlic n butter breadstick";
  price =UberEats.search(food);
   System.out.println(" Price of the food is "+price);
    food = "Mexican pizza";
  price =UberEats.search(food);
   System.out.println(" Price of the food is "+price);
    food = "Tomato sauce pasta";
  price =UberEats.search(food);
   System.out.println(" Price of the food is "+price);
    food = "Masala sandwich";
  price =UberEats.search(food);
   System.out.println(" Price of the food is "+price);
    food = "Carrot halwa";
  price =UberEats.search(food);
   System.out.println(" Price of the food is "+price);
   food = "Paneer manchuri";
  price =UberEats.search(food);
   System.out.println(" Price of the food is "+price);
   
   
   food = "Oreo milkshake";
  price =UberEats.search(food , 1);
   System.out.println(" Price of the food is "+price);
    food = "Chocolate milkshake";
  price =UberEats.search(food , 2);
   System.out.println(" Price of the food is "+price);
    food = "Blueberry shake";
  price =UberEats.search(food , 3);
   System.out.println(" Price of the food is "+price);
    food = "Red sauce pasta";
  price =UberEats.search(food , 4);
   System.out.println(" Price of the food is "+price);
    food = "macroni";
  price =UberEats.search(food , 5);
   System.out.println(" Price of the food is "+price);
    food = "Veg noodles";
  price =UberEats.search(food , 3);
   System.out.println(" Price of the food is "+price);
    food = "Rasam rice";
  price =UberEats.search(food , 4);
   System.out.println(" Price of the food is "+price);
    food = "Loaded cheese fries";
  price =UberEats.search(food , 3);
   System.out.println(" Price of the food is "+price);
    food = "Loaded fries";
  price =UberEats.search(food , 3);
   System.out.println(" Price of the food is "+price);
    food = "Khara bun";
  price =UberEats.search(food , 3);
   System.out.println(" Price of the food is "+price);
    food = "Dum biriyani";
  price =UberEats.search(food , 3);
   System.out.println(" Price of the food is "+price);
    food = "Galebi";
  price =UberEats.search(food , 9);
   System.out.println(" Price of the food is "+price);
    food = "Pepsi";
  price =UberEats.search(food , 3);
   System.out.println(" Price of the food is "+price);
    food = "Veg mania loaded";
  price =UberEats.search(food , 4);
   System.out.println(" Price of the food is "+price);
    food = "Garlic n butter breadstick";
  price =UberEats.search(food , 3);
   System.out.println(" Price of the food is "+price);
    food = "Mexican pizza";
  price =UberEats.search(food , 3);
   System.out.println(" Price of the food is "+price);
    food = "Tomato sauce pasta";
  price =UberEats.search(food , 3);
   System.out.println(" Price of the food is "+price);
    food = "Masala sandwich";
  price =UberEats.search(food , 3);
   System.out.println(" Price of the food is "+price);
    food = "Carrot halwa";
  price =UberEats.search(food , 3);
   System.out.println(" Price of the food is "+price);
   food = "Paneer manchuri";
  price =UberEats.search(food , 5);
   System.out.println(" Price of the food is "+price);
   }
  }